// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLm-W9ZOt7Rs_fZw8SVnFA6H4e0LytFCI',
    appId: '1:299165668538:web:0c2da82bebd0ca91aa1e83',
    messagingSenderId: '299165668538',
    projectId: 'wazker-29798',
    authDomain: 'wazker-29798.firebaseapp.com',
    storageBucket: 'wazker-29798.firebasestorage.app',
    measurementId: 'G-G59ZB1VS3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFz5khT7YX8qjV5BKQ6NyuEBmpzv9yBA',
    appId: '1:299165668538:android:aa4502c6fd37df33aa1e83',
    messagingSenderId: '299165668538',
    projectId: 'wazker-29798',
    storageBucket: 'wazker-29798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKj1_6mnV3o6OhFxMHvPKZSo5Cjp4uWA',
    appId: '1:299165668538:ios:bfacb9bc29d2640caa1e83',
    messagingSenderId: '299165668538',
    projectId: 'wazker-29798',
    storageBucket: 'wazker-29798.firebasestorage.app',
    iosBundleId: 'com.example.wazker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKj1_6mnV3o6OhFxMHvPKZSo5Cjp4uWA',
    appId: '1:299165668538:ios:bfacb9bc29d2640caa1e83',
    messagingSenderId: '299165668538',
    projectId: 'wazker-29798',
    storageBucket: 'wazker-29798.firebasestorage.app',
    iosBundleId: 'com.example.wazker',
  );
}
